### PR TITLE
null safety support

### PR DESCRIPTION
**Pull request by ufukhawk**
null safety support

### CODE REVIEW

**Comment by emrekaplanek** [comment]
We are waiting for null-safety support

**Comment by caravanat** [comment]
Would really appreciate null-safety support.

**Comment by Tomucha** [comment]
I guess it's safe to say that this is dead. @ufukhawk you seem like you know what you are doing :-) Do you want to fork this package and publish as new one?

**Comment by Tomucha** [comment]
See? https://github.com/anish-adm Last activity was 2019 :-/

**Comment by ufukhawk** [comment]
> See? https://github.com/anish-adm Last activity was 2019 :-/

Ready :) https://pub.dev/packages/safe_device/versions/1.0.0

**Comment by ufukhawk** [comment]
> Would really appreciate null-safety support.

https://github.com/ufukhawk/safe_device

**Comment by ufukhawk** [comment]
> We are waiting for null-safety support

https://github.com/ufukhawk/safe_device

**Comment by Tomucha** [comment]
@ufukhawk That's the spirit!

**Pull request closed without merging**
